# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/huyquang/huyquang/SelfProject/Job/datn_hoang/resources/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.combo_options = QtWidgets.QComboBox(self.groupBox)
        self.combo_options.setGeometry(QtCore.QRect(0, 40, 100, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_options.sizePolicy().hasHeightForWidth())
        self.combo_options.setSizePolicy(sizePolicy)
        self.combo_options.setMinimumSize(QtCore.QSize(0, 0))
        self.combo_options.setObjectName("combo_options")
        self.combo_options.addItem("")
        self.combo_options.addItem("")
        self.btn_choose_file = QtWidgets.QPushButton(self.groupBox)
        self.btn_choose_file.setGeometry(QtCore.QRect(100, 38, 100, 26))
        self.btn_choose_file.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_choose_file.setObjectName("btn_choose_file")
        self.qline_limit_person = QtWidgets.QLineEdit(self.groupBox)
        self.qline_limit_person.setGeometry(QtCore.QRect(108, 90, 87, 21))
        self.qline_limit_person.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qline_limit_person.setObjectName("qline_limit_person")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(1, 93, 100, 16))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_start = QtWidgets.QPushButton(self.groupBox)
        self.btn_start.setGeometry(QtCore.QRect(-2, 130, 100, 26))
        self.btn_start.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.groupBox)
        self.btn_stop.setGeometry(QtCore.QRect(101, 130, 100, 26))
        self.btn_stop.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_stop.setObjectName("btn_stop")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        self.qframe_widget = QtWidgets.QFrame(self.centralwidget)
        self.qframe_widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qframe_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qframe_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qframe_widget.setObjectName("qframe_widget")
        self.gridLayout.addWidget(self.qframe_widget, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.combo_options.setItemText(0, _translate("MainWindow", "Image"))
        self.combo_options.setItemText(1, _translate("MainWindow", "Video"))
        self.btn_choose_file.setText(_translate("MainWindow", "Choose File"))
        self.label_2.setText(_translate("MainWindow", "Limit Person"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
