# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/widget_draw.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDraw(object):
    def setupUi(self, WidgetDraw):
        WidgetDraw.setObjectName("WidgetDraw")
        WidgetDraw.resize(519, 443)
        self.gridLayout = QtWidgets.QGridLayout(WidgetDraw)
        self.gridLayout.setObjectName("gridLayout")
        self.qlabel_frame = QtWidgets.QLabel(WidgetDraw)
        self.qlabel_frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout.addWidget(self.qlabel_frame, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(WidgetDraw)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border: 2px solid black;\n"
"border-radius: 6px;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_apply = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_apply.sizePolicy().hasHeightForWidth())
        self.btn_apply.setSizePolicy(sizePolicy)
        self.btn_apply.setStyleSheet("QPushButton {\n"
"            background-color: rgb(255, 255, 255); \n"
"        }\n"
"QPushButton:pressed {\n"
"            background-color: rgb(127, 127, 127);\n"
"        }")
        self.btn_apply.setObjectName("btn_apply")
        self.gridLayout_2.addWidget(self.btn_apply, 0, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setStyleSheet("QPushButton {\n"
"            background-color: rgb(255, 255, 255); \n"
"        }\n"
"QPushButton:pressed {\n"
"            background-color: rgb(127, 127, 127);\n"
"        }")
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_2.addWidget(self.btn_clear, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(WidgetDraw)
        QtCore.QMetaObject.connectSlotsByName(WidgetDraw)

    def retranslateUi(self, WidgetDraw):
        _translate = QtCore.QCoreApplication.translate
        WidgetDraw.setWindowTitle(_translate("WidgetDraw", "Form"))
        self.qlabel_frame.setText(_translate("WidgetDraw", "TextLabel"))
        self.btn_apply.setText(_translate("WidgetDraw", "Apply"))
        self.btn_clear.setText(_translate("WidgetDraw", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetDraw = QtWidgets.QWidget()
    ui = Ui_WidgetDraw()
    ui.setupUi(WidgetDraw)
    WidgetDraw.show()
    sys.exit(app.exec_())
