# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/huyquang/huyquang/SelfProject/Job/datn_hoang/resources/ui/widget_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetImage(object):
    def setupUi(self, WidgetImage):
        WidgetImage.setObjectName("WidgetImage")
        WidgetImage.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(WidgetImage)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(WidgetImage)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setStyleSheet("background-color: rgb(173, 211,230);\n"
"border: 2px solid black;\n"
"border-radius: 6px")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.qlabel_num_of_person = QtWidgets.QLabel(self.groupBox_3)
        self.qlabel_num_of_person.setGeometry(QtCore.QRect(190, 30, 121, 31))
        self.qlabel_num_of_person.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qlabel_num_of_person.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_num_of_person.setObjectName("qlabel_num_of_person")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 121, 31))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.qlabel_frame = QtWidgets.QLabel(WidgetImage)
        self.qlabel_frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout.addWidget(self.qlabel_frame, 0, 0, 1, 1)

        self.retranslateUi(WidgetImage)
        QtCore.QMetaObject.connectSlotsByName(WidgetImage)

    def retranslateUi(self, WidgetImage):
        _translate = QtCore.QCoreApplication.translate
        WidgetImage.setWindowTitle(_translate("WidgetImage", "Form"))
        self.qlabel_num_of_person.setText(_translate("WidgetImage", "0"))
        self.label_5.setText(_translate("WidgetImage", "Number of person"))
        self.qlabel_frame.setText(_translate("WidgetImage", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetImage = QtWidgets.QWidget()
    ui = Ui_WidgetImage()
    ui.setupUi(WidgetImage)
    WidgetImage.show()
    sys.exit(app.exec_())
