# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/huyquang/huyquang/SelfProject/Job/datn_hoang/resources/ui/widget_video.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetVideo(object):
    def setupUi(self, WidgetVideo):
        WidgetVideo.setObjectName("WidgetVideo")
        WidgetVideo.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(WidgetVideo)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(WidgetVideo)
        self.groupBox_2.setStyleSheet("background-color: rgb(173, 221, 230);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qlabel_frame = QtWidgets.QLabel(self.groupBox_2)
        self.qlabel_frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout_2.addWidget(self.qlabel_frame, 0, 0, 1, 1)
        self.qlabel_heatmap = QtWidgets.QLabel(self.groupBox_2)
        self.qlabel_heatmap.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qlabel_heatmap.setObjectName("qlabel_heatmap")
        self.gridLayout_2.addWidget(self.qlabel_heatmap, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(WidgetVideo)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setStyleSheet("background-color: rgb(173, 221, 230);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.qlabel_num_of_person = QtWidgets.QLabel(self.groupBox_3)
        self.qlabel_num_of_person.setGeometry(QtCore.QRect(190, 66, 121, 31))
        self.qlabel_num_of_person.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qlabel_num_of_person.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel_num_of_person.setObjectName("qlabel_num_of_person")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 66, 121, 31))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.checkbox_draw_polygon = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkbox_draw_polygon.setGeometry(QtCore.QRect(20, 20, 121, 20))
        self.checkbox_draw_polygon.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.checkbox_draw_polygon.setObjectName("checkbox_draw_polygon")
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)

        self.retranslateUi(WidgetVideo)
        QtCore.QMetaObject.connectSlotsByName(WidgetVideo)

    def retranslateUi(self, WidgetVideo):
        _translate = QtCore.QCoreApplication.translate
        WidgetVideo.setWindowTitle(_translate("WidgetVideo", "Form"))
        self.qlabel_frame.setText(_translate("WidgetVideo", "TextLabel"))
        self.qlabel_heatmap.setText(_translate("WidgetVideo", "TextLabel"))
        self.qlabel_num_of_person.setText(_translate("WidgetVideo", "0"))
        self.label_5.setText(_translate("WidgetVideo", "Number of person"))
        self.checkbox_draw_polygon.setText(_translate("WidgetVideo", "Draw Polygon"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetVideo = QtWidgets.QWidget()
    ui = Ui_WidgetVideo()
    ui.setupUi(WidgetVideo)
    WidgetVideo.show()
    sys.exit(app.exec_())
